name: AWS S3 Deploy
on:
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: credential
        uses: aws-actions/configure-aws-credentials@v1
        with: # usesで使うActionに与えるパラメータ（引数）は「with」要素で指定する。
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
#      - name: Output file contents
#        run: |
#          pwd
#          ls
      - name: AWS SSM Send-Command
        uses: peterkimzz/aws-ssm-send-command@0.0.1
        with:
          instance_ids: i-01dbefa027673eff6
          commands: git log --oneline
          working_directory: /home/ec2-user/discord
