name: AWS S3 Deploy
jobs:
  s3deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Publish to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: us-east-2
      - name: Copy files to S3 with the AWS CLI
         run: |
         aws s3 sync . s3://mokumokuonlinestudyroom-test-githubaction
on:
  push:  
    branches:
      - master
