name: AWS S3 Deploy
on:
  push:
    branches:
      - master
jobs:
  s3deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Publish to AWS S3
        uses: aws-actions/configure-aws-credentials@v1
        with: # usesで使うActionに与えるパラメータ（引数）は「with」要素で指定する。
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ap-northeast-1
      - name: Output file contents
        run: |
          pwd
          ls
